### PR TITLE
Update api.rb

### PR DESCRIPTION
**Pull request by nigel**
checks for a period in the URL

### CODE REVIEW

**Comment by chinstorff** [comment]
If you're trying to validate URLs, consider using [regular expressions](http://ruby-doc.org/core-2.1.1/Regexp.html) ([site to check expressions](http://rubular.com/)).

However, URLs are incredibly complex. For example, not all URLs containing a "." are valid, such as "moose.head@".

Consider whether or not validation is actually necessary. Is there a security or user experience problem if the user can enter any non-empty string of text?

**Comment by nigel** [comment]
I assumed checking the validation of URLs would be a cool addition to the url shortener

a list of valid domain extensions could be found here http://data.iana.org/TLD/tlds-alpha-by-domain.txt
wouldn't it be easier to check the link's extension in the text file to validate the url?

**Comment by tekknolagi** [comment]
If you want to dive into the incredibly annoyingly complex field of email/URL/bitcoin address validation, go for it. I do not, however, particularly want to have to manage this kind of code. Please ensure that if you submit a proper patch, it conforms to existing informal style, has decent documentation, and a good commit message.

**Comment by nigel** [comment]
I'll give it a shot

Thanks (:

**Pull request closed without merging**
